addons:
  apt:
    packages:
      - libboost-all-dev
      - libapr1-dev
      - libc6-dev
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
